from apify_client import ApifyClient
import os
from dotenv import load_dotenv

# Load the environment variables from your .env file
load_dotenv()

# 1. Paste your token here
APIFY_API_TOKEN = os.getenv("APIFY_API_TOKEN")

def get_youtube_transcript(video_url: str) -> str:
    """Fetches the transcript of a YouTube video using Apify."""
    print(f"Starting Apify Actor to fetch transcript for: {video_url}...")
    
    # Check if the token was loaded properly to avoid silent failures
    if not APIFY_API_TOKEN:
        return "Error: APIFY_API_TOKEN is not set in environment or .env file."
        
    client = ApifyClient(APIFY_API_TOKEN)

    # We switched to a more robust actor and set "outputFormat" to "text" 
    # so we don't have to manually join the timestamps!
    run_input = {
        "urls": [{"url": video_url}],
        "outputFormat": "text",
        # Add these lines to accept any language, including auto-generated ones
        "languages": ["en", "hi", "en-US", "hi-IN"], 
        "getAutoGenerated": True
    }

    # Run the new Actor
    run = client.actor("supreme_coder/youtube-transcript-scraper").call(run_input=run_input)

    # FIX 1: Use .default_dataset_id (attribute) instead of dictionary access
    dataset_id = run.default_dataset_id
    
    # Fetch results from the dataset
    items = client.dataset(dataset_id).list_items().items
    
    if not items:
        return "Error: No transcript found or video doesn't have captions."
    
    # The first item in the dataset contains our transcript data
    transcript_data = items[0]
    
    # Since we requested text format, the transcript is already a clean string
    if 'transcript' in transcript_data:
        return transcript_data['transcript']
        
    return "Error: Transcript format was unexpected."

# --- Test the script ---
if __name__ == "__main__":
    # Testing with the video that broke the last actor!
    test_url = "https://youtu.be/-dUiRtJ8ot0?si=48QWO8lEqUTo8V_j"
    
    transcript = get_youtube_transcript(test_url)
    
    print("\n--- Extracted Transcript ---")
    print(transcript[:500] + "...\n\n(Transcript truncated for preview)")